#!/usr/bin/env python3
"""
dpc_complaint_drafter.py
Scans tracker for overdue SARs and auto-generates DPC complaint markdown letters.

Usage: python dpc_complaint_drafter.py <tracker.csv> 'Your Full Name' [output_dir]
"""

import csv
import os
import sys
from datetime import datetime

TEMPLATE = '''# Complaint to Data Protection Commission

**Date:** {date}
**Complainant:** {name}
**Respondent:** {agency}
**Request ID:** {req_id}

---

To the Data Protection Commission,
21 Fitzwilliam Square South,
Dublin 2, D02 RD28
Email: info@dataprotection.ie

## Subject: Formal Complaint under Section 111 Data Protection Act 2018

I wish to lodge a formal complaint against **{agency}** for failure to comply with a Subject Access Request submitted on **{date_sent}**.

### 1. Background
On {date_sent}, I submitted a Subject Access Request under Article 15 GDPR / Section 91 Data Protection Act 2018. The statutory deadline for response was **{deadline}**.

### 2. Failure to Comply
As of today ({date}), I have received:
- [ ] No acknowledgement
- [ ] No request for extension
- [ ] A refusal without valid legal basis
- [ ] An incomplete response

### 3. Requested Action
I request that the DPC investigate this breach of my data subject rights and compel **{agency}** to comply with its statutory obligations.

### 4. Evidence
- Original SAR reference: {ref_num}
- Method of sending: {method}
- Letter hash (forensic): {letter_hash}
- Attached: Copy of original request, proof of sending, and correspondence log.

Yours faithfully,

{name}

---
*Generated by ireland-sar-toolkit v2.1*
'''


def draft_complaints(tracker_path, user_name, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    today = datetime.now().strftime("%d %B %Y")

    with open(tracker_path, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            deadline = row.get("Day_30_Deadline", "")
            if not deadline:
                continue

            try:
                dl = datetime.strptime(deadline, "%Y-%m-%d")
            except ValueError:
                continue

            if dl > datetime.now():
                continue  # Not overdue yet

            agency = row.get("Agency", "Unknown Agency")
            req_id = row.get("Request_ID", "N/A")
            date_sent = row.get("Date_Sent", "Unknown")
            method = row.get("Method_Sent", "Unknown")
            ref_num = row.get("Reference_Number", "N/A")
            letter_hash = row.get("Letter_Hash", "N/A")

            content = TEMPLATE.format(
                date=today,
                name=user_name,
                agency=agency,
                req_id=req_id,
                date_sent=date_sent,
                deadline=dl.strftime("%d %B %Y"),
                ref_num=ref_num,
                method=method,
                letter_hash=letter_hash
            )

            safe_agency = "".join(c if c.isalnum() else "_" for c in agency)
            filename = f"DPC_Complaint_{safe_agency}_{dl.strftime('%Y%m%d')}.md"
            path = os.path.join(out_dir, filename)
            with open(path, "w") as f:
                f.write(content)
            print(f"Drafted: {path}")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python dpc_complaint_drafter.py <tracker.csv> 'Your Full Name' [output_dir]")
        sys.exit(1)
    draft_complaints(sys.argv[1], sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else "output")
